### ISSUE TITLE
BUILD FAILED on node v5.9.0 npm 3.7.3 and xcode 7.2

### ISSUE THREAD

**Issue by chromonav** [bluedaniel/Kakapo-native#7]
Failed to build app on node v5.9.0 npm 3.7.3 and xcode 7.2.
Since npm start was giving not defined error.
I first did 
'rnpm link' and then 
'react-native run-ios'

Got the Following is build error  
`*\* BUILD FAILED **

The following build commands failed:
    PhaseScriptExecution Run\ Script build/Build/Intermediates/KakapoNative.build/Debug-iphonesimulator/KakapoNative.build/Script-B110D0D71CB7186A00DA90CF.sh
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/KakapoNative.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/chromonav/Documents/projects/kaka/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/KakapoNative.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```
at checkExecSyncError (child_process.js:469:13)
at Object.execFileSync (child_process.js:489:13)
at _runIOS (runIOS.js:83:34)
at runIOS.js:24:5
at tryCallTwo (/Users/chromonav/Documents/projects/kaka/node_modules/promise/lib/core.js:45:5)
at doResolve (/Users/chromonav/Documents/projects/kaka/node_modules/promise/lib/core.js:200:13)
at new Promise (/Users/chromonav/Documents/projects/kaka/node_modules/promise/lib/core.js:66:3)
at Array.runIOS (runIOS.js:23:10)
at Object.run (/Users/chromonav/Documents/projects/kaka/node_modules/react-native/local-cli/cli.js:86:13)
at Object.<anonymous> (/Users/chromonav/.nvm/versions/node/v5.9.0/lib/node_modules/react-native-cli/index.js:73:7)
```

`
also not working on android  build error:
- Where:
  Build file '/Users/chromonav/Documents/projects/kaka/android/app/build.gradle' line: 98
- What went wrong:
  A problem occurred evaluating project ':app'.
  
  > /Users/chromonav/Documents/projects/kaka/android/app/keys.properties (No such file or directory)

**Comment by bluedaniel** [comment]
Hey @chromonav, I know exactly what the issue is.

I recently installed Twitters CrashAnalytics into the project and they require API Keys to run. Ill have to have a look at how I can make this work in the repo or remove it altogether.

It's quite difficult to determine what should and shouldn't be in this public repo at times 😄 

Thanks for the report though, I'll try and fix it tonight.

**Comment by chromonav** [comment]
thanks a lot @bluedaniel.
you don't need remove Crashlytics though
pl can you tell abt configuring it into the app.
